# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 460547347a178158b07cc77182485d5acba6f197a17ddb3ce776c87623045ef0cce325bc1025d214a77f8e47e0be4657b5cea0ad8e347bb29376a5b87be8d81d

test:
  secret_key_base: a1e29b7c63a1b37e0b619f85c270d074aeaf9424fffae8833176f30d421a43132efc4d9dbaafd672908729a32851c92877804af179bc56178fd7985fd0e79196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
